### PR TITLE
Update lmyoslib.c for new lua 5.4 version

### PR DESCRIPTION
**Pull request by LocutusOfBorg**
Fix lua 5.4 compatibility, due to deprecated LUA_QS macro

### CODE REVIEW

**Comment by LocutusOfBorg** [comment]
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=964680 for reference

**Comment by hosiet** [comment]
Hi @LocutusOfBorg ,

Thanks for the forwarded patch. The upstream of ibus-pinyin is https://github.com/ibus/ibus-pinyin , not this repository. If you have time, can you open the Pull Request against the new repo?

**Comment by LocutusOfBorg** [comment]
oops!

**Comment by LocutusOfBorg** [comment]
https://github.com/ibus/ibus-pinyin/pull/10

**Pull request closed without merging**
